AWSTemplateFormatVersion: '2010-09-09'

Description: ASG of Apache HTTP Server with ALB and CloudWatch Agent

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Application Environment
      Parameters:
      - pEnvPurpose
    - Label:
        default: Application Ownership
      Parameters:
      - pOwnerEmail
    - Label:
        default: Cost Accounting
      Parameters:
      - pCostCenter
    - Label:
        default: Organization
      Parameters:
        - pOrg
    - Label:
        default: Network
      Parameters:
      - pVpcName
    - Label:
        default: Load Balancer
      Parameters:
      - pAlbIngressCidr
      - pAlbIngressPrefixListId
    - Label:
        default: Auto Scaling
      Parameters:
      - pServerCount
      - pInstanceType
    - Label:
        default: Data and Privacy Classification
      Parameters:
      - pDataClass
      - pPrivacyClass
    - Label:
        default: Template Repository
      Parameters:
      - pArtifactBucket

    ParameterLabels:
      pEnvPurpose:
        default: Environment Purpose (10 characters or less)
      pCostCenter:
        default: Enterprise Standard Cost Center (nnnnnn)
      pVpcName:
        default: VPC Name (name of existing VPC)
      pOrg:
        default: Business Scope
      pAlbIngressCidr:
        default: Application Load Balancer (ALB) Allowed Ingress CIDR IP Range
      pAlbIngressPrefixListId:
        default: Application Load Balancer (ALB) Allowed Prefix List ID
      pServerCount:
        default: Number of EC2 Instances
      pInstanceType:
        default: EC2 Instance Type
      pDataClass:
        default: Standard Data Classification
      pPrivacyClass:
        default: Standard Privacy Classification
      pArtifactBucket:
        default: Template Repository

Parameters:
  pEnvPurpose:
    Type: String
    Description: Used to qualify resource names. 10 characters max.
    AllowedPattern: '^[a-zA-Z0-9-_]{1,10}$'

  pVpcName:
    Description: Name of the existing VPC
    Type: String

  pOrg:
    Type: String
    Description: Used to qualify resource tag names
    Default: acme

  pAlbIngressCidr:
    Description: IP address range that can be used to access the ALB
    Type: String
    Default: ''

  pAlbIngressPrefixListId:
    Description: ID of the prefix list representing the service that can be used to access the ALB
    Type: String
    Default: ''

  pServerCount:
    Description: Number of Amazon EC2 instances to launch for the web server
    Type: Number
    Default: '1'

  pInstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3a.micro
    AllowedValues:
      - t3a.micro
      - t3a.small
      - t3a.medium
    ConstraintDescription: must be a valid EC2 instance type.

  pOwnerEmail:
    Type: String
    Description: Email address of individiual or distribution list
    AllowedPattern: '^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'

  pCostCenter:
    Type: String
    Description: Standard cost center
    AllowedPattern: '[0-9]{6}'

  pDataClass:
    Type: String
    Description: Standard data classification
    Default: internal

  pPrivacyClass:
    Type: String
    Description: Standard data privacy risk classification
    Default: low

  pArtifactBucket:
    Type: String
    Description: Name of existing S3 bucket where the CloudFormation template reside

Resources:
  rStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  !Sub https://s3.amazonaws.com/${pArtifactBucket}/cfn-templates/samples-simple-http-server.yml
      Parameters:
        pEnvPurpose:             !Ref pEnvPurpose
        pVpcName:                !Ref pVpcName
        pAlbIngressCidr:         !Ref pAlbIngressCidr
        pAlbIngressPrefixListId: !Ref pAlbIngressPrefixListId
        pServerCount:            !Ref pServerCount
        pInstanceType:           !Ref pInstanceType
      Tags:
        - Key: !Sub ${pOrg}-service-id
          Value: samples.http
        - Key: !Sub ${pOrg}-env-purpose
          Value: !Ref pEnvPurpose
        - Key: !Sub ${pOrg}-owner
          Value: !Ref pOwnerEmail
        - Key: !Sub ${pOrg}-cost-center
          Value: !Ref pCostCenter
        - Key: !Sub ${pOrg}-data-class
          Value: !Ref pDataClass
        - Key: !Sub ${pOrg}-privacy-class
          Value: !Ref pPrivacyClass
